### ISSUE TITLE
Too long INFO filed fails quality control

### ISSUE THREAD

**Issue by Zepeng-Mu** [genepi/imputationserver#14] opened 2019-03-19 18:54 UTC
Hi, I am using the server to impute the VCF file with many (20-30) INFO fields. The Quality Control step always fails without any logfiles or error messages for trouble shooting. I then used VCFtools to remove all the INFO fields and the imputation is OK now.

I am wondering why too many INFO fields in my VCF files would cause QC to fail.

**Comment by seppinho** [comment] 2019-03-20 10:27
Thanks for letting us know. Can you provide a simple VCF file (including the header and some data lines) so that we can reproduce the error?

**Comment by seppinho** [comment] 2019-03-20 13:59
Do you have a file link for me? Thanks

**Comment by Zepeng-Mu** [comment] 2019-03-20 14:02
Yes, this is the [VCF](https://www.ebi.ac.uk/arrayexpress/experiments/E-GEUV-1/files/genotypes/).

**Comment by seppinho** [comment] 2019-03-20 14:26
Imputation Server reports 
`The provided VCF file is malformed. Error during index creation: [tabix] was bgzip used to compress this file?`
My local tabix command fails as well.

**Comment by Zepeng-Mu** [comment] 2019-03-20 14:52
Thank you. Actually, I did some filtering on the VCF file, MAF, missingness like that. Then I used bgzip to compress the VCF file, so I did not get this error. I can attach an image of my error information:

[![error](https://i.postimg.cc/50FQYRSF/Screen-Shot-2019-03-20-at-9-49-38-AM.png)](https://postimg.cc/jwtSBv9s)

**Comment by seppinho** [comment] 2019-03-21 11:13
Thanks. I tested the file with the new minimac4 pipeline (currently beta), and everything works as expected. I can activate the pipeline for you to see if the problem is solved (I only tested 1 file so far). Would that work for you?

**Comment by Zepeng-Mu** [comment] 2019-03-21 13:38
Thank you so much. I can just do the imputation without INFO fields, as they are not necessary for me. Since I have imputed several other genomes, I think it is better to keep this one consistent. But I am very willing to try other pipelines in the future!!

**Comment by seppinho** [comment] 2019-03-21 13:54
Thanks! Closing this issue for now.

**Closed by seppinho** 2019-03-21 13:54 UTC
